export type Section =
  | 'dashboard'
  | 'agenda'
  | 'clientes'
  | 'vehiculos'
  | 'inventario'
  | 'mecanicos'
  | 'cotizaciones'
  | 'ordenes'
  | 'ventas'
  | 'informes'
  | 'creditos'
  | 'gastos'
  | 'reportes'
  | 'anticipos'
  | 'vacaciones'
  | 'proveedores'
  | 'config'
